// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGtGh-TEVFcLEshpwzccu-zgAy5HWRmjA',
    appId: '1:156176781420:android:97e256e2f95d40376d0849',
    messagingSenderId: '156176781420',
    projectId: 'firebase-project-practice',
    storageBucket: 'firebase-project-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVFBNSsGtLLjhyeKbjnOtSdRLB4LE-Vw',
    appId: '1:156176781420:ios:b73f851abe0ce5426d0849',
    messagingSenderId: '156176781420',
    projectId: 'firebase-project-practice',
    storageBucket: 'firebase-project-practice.appspot.com',
    iosClientId: '156176781420-j4f8u5iplvnk5kml8clr0ghd5e8thb16.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );
}
